config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  get 'users/new'

  resources :categories do
    resources :subcategories
  end

  resources :listings do
    collection do
      get 'search'
    end
  end

  root 'categories#index'

  match '/help', to: 'pages#help', via: :get
  match '/scams', to: 'pages#scams', via: :get
  match '/safety', to: 'pages#safety', via: :get
  match '/about', to: 'pages#about', via: :get
  match '/contact', to: 'pages#contact', via: :get
  match '/privacy', to: 'pages#privacy', via: :get
  match '/terms', to: 'pages#terms', via: :get
  match '/subcategories/find_by_category', to: 'subcategories#find_by_category', via: :post
  match '/categories/:id', to: 'categories#show', via: :get
  match '/map', to: 'pages#map', via: :get
end

app/models/category.rb
class Category < ActiveRecord::Base
	#Has a one to many relationship with subcategory
	has_many :subcategories
	has_many :listings
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	#The index page of our categories controller
	def index
		@categories = Category.all
		@housing = @categories[0]
		@roommates = @categories[1]
		@forsale = @categories[2]
	end

	def show
		@listings = Listing.where(category_id: params[:id])
	end
end

app/views/categories/index.html.erb
<body>
  <div class="mainbtn-container">
    <div class="image-wrap">
      <%= link_to (image_tag image_url('housing.png')),  category_path(@housing), {:class => 'btn btn-large btn-danger'} %>
    </div>
    <div class="image-wrap">
      <%= link_to (image_tag image_url('roommates.png')),  category_path(@roommates), {:class => 'btn btn-large btn-danger'} %>
    </div>
    <div class="image-wrap">
      <%= link_to (image_tag image_url('buysell.png')),  category_path(@forsale), {:class => 'btn btn-large btn-danger'} %>
    </div>
  </div>
</body>

app/views/categories/show.html.erb
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <a href="#"><%= link_to 'shiplist', root_path %></a>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
     <div class="newest">newest</div>
     <div class="oldest">oldest</div>
     <div class="highest-price">highest-price</div>
     <div class="lowest-price">lowest-price</div>
   </div>
  <ul class="list-margin">
    <% if @listings.present? %>
      <% @listings.each do |listing| %>
      <li>
        <span>
          <%= listing.created_at.strftime('%B %d, %Y') %>
        </span>
        <%= link_to listing.title, listing %>
      </li>
      <% end %>
    <% else %>
      <p>No listings found!</p>
    <% end %>
  </ul>
</div>