config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  get 'users/new'

  resources :categories do
    resources :subcategories
  end

  resources :listings do
    collection do
      get 'search'
    end
  end

  root 'categories#index'

  match '/help', to: 'pages#help', via: :get
  match '/scams', to: 'pages#scams', via: :get
  match '/safety', to: 'pages#safety', via: :get
  match '/about', to: 'pages#about', via: :get
  match '/contact', to: 'pages#contact', via: :get
  match '/privacy', to: 'pages#privacy', via: :get
  match '/terms', to: 'pages#terms', via: :get
  match '/subcategories/find_by_category', to: 'subcategories#find_by_category', via: :post
  match '/categories/:id', to: 'categories#show', via: :get
  match '/map', to: 'pages#map', via: :get
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Ship List</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.2/dist/leaflet.css" />
		<script src="https://unpkg.com/leaflet@1.0.2/dist/leaflet.js"></script>
	</head>
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<%= link_to 'SHIP LIST', root_path, class: "navbar-brand"%>
			</div>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in?%>
				<li><%= link_to 'POST AD', new_listing_path %></li>
				<li><%= link_to 'LOG OUT', destroy_user_session_path, :method => :delete %></li>
				<% else %>
				<li><%= link_to 'SIGN UP', new_user_registration_path %></li>
				<li><%= link_to 'LOG IN', new_user_session_path %></li>
				<% end %>
				<li>
					<%= form_tag search_listings_path, :class => 'navbar-form', :method => 'get' do %>
					<p>
						<%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search' %>
						<%= submit_tag "Search", :class => 'btn btn-default', :type => "submit", :name => nil %>
					</p>
					<% end %>
				</li>
			</ul>
		</div>
	</nav>
	<body>
		<%= render 'layouts/messages' %>
		<%= yield %>
	</body>
	<footer class="footer">
		<p>
			<%= link_to 'Help and Faq', help_path%> -
			<%= link_to 'Avoid Scams and Fraud', scams_path%> -
			<%= link_to 'Terms of Use', terms_path%> -
			<%= link_to 'Privacy Policy', privacy_path%> -
			<%= link_to 'About Shiplist', about_path%> -
			<%= link_to 'Contact Us', contact_path%>
		</p>
	</footer>
	<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
		<div class="modal-dialog">
			<div class="loginmodal-container">
				<h1>Login to Your Account</h1><br>
				<form>
					<input type="text" name="user" placeholder="Username">
					<input type="password" name="pass" placeholder="Password">
					<input type="submit" name="login" class="login loginmodal-submit" value="Login">
				</form>
				
				<div class="login-help">
					<a href="#">Register</a> - <a href="#">Forgot Password</a>
				</div>
			</div>
		</div>
	</div>
</html>